### ISSUE TITLE
Add text to first GZ question

### ISSUE THREAD

**Issue by vrooje** [zooniverse/Galaxy-Zoo#185]
GZ has no tutorial and doesn't currently even tell people to classify the galaxy in the center of the image.

Proposed fix: add text to the interface -- e.g.

![gzaddedtxt](https://cloud.githubusercontent.com/assets/2357126/5168194/eb186778-73f4-11e4-9b31-808d67b0a0ac.jpg)

Font size and format subject to readability/design criteria, obviously...

**Comment by vrooje** [comment]
@chrissnyder Did this ever get done? Just popped by to check past issues and noticed this.

**Comment by chrissnyder** [comment]
Definitely wasn't done. Is now, will be live in a moment.
