### ISSUE TITLE
Ids for new surveys and workflows

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#188]
e556370ff60e522810e75bf66580787671405f50 

Needs Ids for all three of the new surveys and workflowIds for the two new decision trees. Part of pull request https://github.com/zooniverse/Galaxy-Zoo/pull/187

**Comment by murraycu** [comment]
Isn't this all working now?

**Comment by willettk** [comment]
Should be, although yet another new set of images is coming sometime this
week. @chrissnyder is doing spot checking to make sure the transition will
be smooth.

**Comment by murraycu** [comment]
Surely this issue should be closed now?

**Comment by willettk** [comment]
I think so; I'd want the devs to verify that IDs for new surveys are
handled in the same way.

**Comment by willettk** [comment]
Closed with f34ee0917cc78d92268ebb821e4bb97bd609f3d2.
