### ISSUE TITLE
User reporting getting repeats

### ISSUE THREAD

**Issue by DarrenMcRoy** [zooniverse/Galaxy-Zoo#191]
A user has reported being served these images multiple times:

AGZ0004v06, AGZ0001qgw, AGZ0005580 and maybe AGZ0001v1i

Any reason this should be happening?

Thanks!

**Comment by edpaget** [comment]
Are they logged in? Can you link to the report?

**Comment by DarrenMcRoy** [comment]
The user's name is @deuterijum ... it was forwarded to me by a moderator.

One of us could message the user directly if we needed more info?
