### ISSUE TITLE
Example images missing for clickthrough for sloan_singleband

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#197]
When clicking on the "Examples" help button in the main interface, thumbnails of the example images are visible. Clicking on them, however, brings up a missing image and the error below

![screen shot 2015-05-13 at 6 33 12 pm](https://cloud.githubusercontent.com/assets/2285931/7623319/899f6386-f99e-11e4-87ec-0d0dc906c502.png)

```
http://static.zooniverse.org/www.galaxyzoo.org/images/examples/sloan_singleband-0_a-1_1.jpg 
Failed to load resource: the server responded with a status of 403 (Forbidden)
```

**Comment by murraycu** [comment]
This is fixed by my commits here: https://github.com/zooniverse/Galaxy-Zoo/issues/198.

**Comment by murraycu** [comment]
Pull Request #198 was merged, so this can be closed.
