### ISSUE TITLE
New icons for DECaLS and Illustris images

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#206]
For @heathv - we need new icons for two new datasets, similar to the ones we already have for SDSS, HST, and UKIDSS. The new data are for DECaLS (Dark Energy Camera on the CTIO Blanco Telescope) and simulated images from the Illustris project.

Example: https://github.com/zooniverse/Galaxy-Zoo/blob/master/public/images/gz-icon-ukidss.png

**Comment by chrissnyder** [comment]
For further reference:

SDSS: https://github.com/zooniverse/Galaxy-Zoo/blob/master/public/images/gz-icon-sdss.png
Hubble: https://github.com/zooniverse/Galaxy-Zoo/blob/master/public/images/gz-icon-hubble.png

**Comment by heathv** [comment]
![decam-icon](https://cloud.githubusercontent.com/assets/4551411/8854314/e885203a-3124-11e5-84a7-75383ac4788f.png) ![sims-icon](https://cloud.githubusercontent.com/assets/4551411/8854315/e887bb56-3124-11e5-8a9c-9216dafebeaf.png)

DECam on the left, simulations on the right. Had to get a little conceptual for 'simulation' but [I pulled from this video clip](http://www.illustris-project.org/movies/illustris_movie_cube_sub_frame.mp4)

If these are too far off, let me know!

**Comment by willettk** [comment]
Love them. Thanks, @heathv!

**Comment by willettk** [comment]
Closed with #209.
