### ISSUE TITLE
New workflow icon for overlapping galaxies

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#210]
The science team has just one new category we want to add to the ```DECaLS``` images. This is for galaxies that overlap with each other along our line of sight, but in reality are very far apart and are NOT physically merging. That means that neither galaxy has its shape distorted by their gravitational pulls, and so you just see them in projection. 

@heathv: below are several example images of this category. Could you make an icon that will appear on the classification page for this option? I think the standard way of handling these has been putting them in one big image (https://github.com/zooniverse/Galaxy-Zoo/blob/master/public/images/workflow.png) and then loading parts of it, although I think a separate icon can work as well. 

![overlapping1](https://cloud.githubusercontent.com/assets/2285931/9141274/0a95f148-3cfd-11e5-83d7-423f473d296f.jpeg)
![overlapping2](https://cloud.githubusercontent.com/assets/2285931/9141273/0a95c074-3cfd-11e5-86fd-56daf355a5ac.jpeg)
![overlapping3](https://cloud.githubusercontent.com/assets/2285931/9141276/0a968f7c-3cfd-11e5-84f1-e532f30f6940.jpeg)
![overlapping4](https://cloud.githubusercontent.com/assets/2285931/9141272/0a9560c0-3cfd-11e5-98eb-02dc5b80250b.jpeg)
![overlapping5](https://cloud.githubusercontent.com/assets/2285931/9141271/0a950b52-3cfd-11e5-8269-6df3e57cbf9a.jpeg)
![overlapping6](https://cloud.githubusercontent.com/assets/2285931/9141275/0a9605b6-3cfd-11e5-8710-2295cfd86faa.jpeg)

**Comment by heathv** [comment]
Does this work? 

![overlapping](https://cloud.githubusercontent.com/assets/4551411/9282940/76a57fb4-4295-11e5-829f-e893c3c5890e.png)

**Comment by willettk** [comment]
Looks great! There are obviously a lot of different orientations and types of galaxies that could overlap, but this is a nice archetype (and they can look at the actual examples for more). Thanks, @heathv!
