### ISSUE TITLE
Running Galaxy Zoo from hem gives 404 on localhost

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#212]
Revisiting #186. I'm trying to get a version of GZ running locally so I can change some of the text describing subjects and science. Using the older version of node (0.10.40) successfully runs:

```
npm install .

./fits/build.rb
./interactive/build.rb

hem server
Starting Server at localhost:9294
```

Opening up localhost:9294 in the browser, though, just yields a 404.

![screen shot 2015-08-11 at 12 26 54 pm](https://cloud.githubusercontent.com/assets/2285931/9204784/496b7f3a-4024-11e5-86b7-38d1787e8ed0.png)

**Comment by edpaget** [comment]
Does `/index.html` work?

**Comment by willettk** [comment]
http://localhost:9294/index.html has the same result.

**Comment by parrish** [comment]
Could you post the result of

`which hem` (should look like ./node_modules/.bin/hem)

and

`node -v` (should be v0.10.x)

**Comment by willettk** [comment]
Aha. 

```which hem``` yielded ```/usr/local/bin/hem```, not the version in this directory. 

Using ```./node_modules/.bin/hem``` and node v.0.10 works. Thanks, @parrish and @edpaget!

**Comment by parrish** [comment]
No problem.  I usually add the local npm .bin path in my bash profile with something like:

``` bash
PATH="./node_modules/.bin:${PATH}"
# usually lots of other path modifications...
export PATH
```

So that when you use `hem`, the first binary bash finds is in the local path if it exists.

**Comment by willettk** [comment]
Good suggestion. Thanks!
