### ISSUE TITLE
Source of text for icons and classification page

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#214]
This may end up being more of a question than a technical issue, but I'm trying to figure out where the text comes from for the question and icon labels on the main classification page. I'd thought that the wording for both was in the relevant decision tree file (eg, https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/lib/sloan_singleband_tree.coffee), but the actual text seem to be pulled from https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/lib/en.coffee. 

What confuses me is that ```en.coffee``` doesn't have question text for every workflow; right now, the master branch only includes **goods_full**, **sloan**, and **candels**. For other surveys/workflows (such as **sloan_singleband** or the upcoming **decals**/**illustris**), where is the text taken from? Just trying to make sure I get the wording right for the next sets of data ...

**Comment by murraycu** [comment]
I wonder about this too. Why didn't you need to do this for the sloan_singleband questions, for instance?

My code to read out the illustris tree as XML for the Android app is failing because this file doesn't contain the text for the illustris questions. But I'd rather avoid the error-prone repetition.

**Comment by chrissnyder** [comment]
Handled in #215 and for reference the text comes from https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/models/question.coffee#L56-L77

**Comment by murraycu** [comment]
Note that the text that's actually used (from en.coffee) is sometimes subtly different than the text in the *_tree.coffee decision-tree files.

Is the title and help text in the *_tree.coffee files actually used anywhere? If not, maybe it should be removed to avoid the impression that it will be used.

**Comment by chrissnyder** [comment]
Embarrased to say "I don't think so", but not 100% sure. There's a lot going on in the codebase (a nice way of saying we should've refactored most of it a long time ago).

And yes, we are definitely looking to get Galaxy Zoo over to Panoptes at some point. Would make managing these workflows much much easier (and accessible via a straight API call!)
