### ISSUE TITLE
Jumbled text in the classification box

### ISSUE THREAD

**Issue by simoneduca** [zooniverse/Galaxy-Zoo#216]
When there are many examples shown the box height increases and the text of Note and Question overlap.
![screen shot 2015-09-03 at 10 35 35](https://cloud.githubusercontent.com/assets/8989606/9655393/9a5a6238-5228-11e5-835c-026395c0f444.png)

**Comment by murraycu** [comment]
I'm seeing this lots recently too. The pull request has a fix.
