### ISSUE TITLE
German translation text does not reliably appear on site when selected in menu

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#240]
I was testing out the new German text in Galaxy Zoo, and it's not reliably loading in the browser every time. The first time I tried, the URL was http://www.galaxyzoo.org/?lang=de, but all the text was in English. Reloading the browser ~10 times, the German text appears roughly 50% of the time, and English the other 50%. My colleagues reported the same problem.

The problem only seems to be with the German text; other languages show on the first load and remain upon all the reloads.

Tested this on Chrome Version 46.0.2490.80 (64-bit).

**Comment by murraycu** [comment]
Confirmed. I see this too when reloading the page, though it seems more like 30% English. I guess there's a server that hasn't been properly updated. Each refresh probably gets the page from a different server, hidden behind some kind of load balancer.

**Comment by willettk** [comment]
This problem seems to have been resolved - reloading roughly a dozen times preserved the German each time. @murraycu, can you confirm?

**Comment by murraycu** [comment]
Confirmed.

**Comment by eatyourgreens** [comment]
This might have been caused by our CloudFront setup caching the json files. If you ping one of us, we can clear the CF cache after an update to a file.

**Comment by willettk** [comment]
Ah - that's good to know. Maybe we should add that to the instructions on adding new text in the README.md file for this repo.
