### ISSUE TITLE
Automatic copying of selected strings for translation

### ISSUE THREAD

**Issue by willettk** [zooniverse/Galaxy-Zoo#244]
The newest workflows for Galaxy Zoo (https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/lib/decals_tree.coffee and https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/lib/illustris_tree.coffee) have a great deal of identical text to existing workflows like https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/lib/sloan_tree.coffee. However, this isn't preserved for any of the non-English translations. 

Is it possible to set up something for the site so that ALL of the existing translations will have certain fields automatically copied? (eg, `decals-6-question` = `sloan-1-question`, etc)? I can make a list of all the duplicate fields if there's a way to implement it.

**Comment by eatyourgreens** [comment]
I'm not familiar with GZ, but can you just reuse translation keys in the source code, or will that break the decision trees?

**Comment by willettk** [comment]
I'm not sure. The only place I've seen the keys being reused is here: https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/models/question.coffee#L56

Would need to experiment if that can be used for individual questions.

**Comment by eatyourgreens** [comment]
Closing this because GZ is on Panoptes now.
