### ISSUE TITLE
Can we add Decals/Illustris data to dev? or reactivate some old subjects?

### ISSUE THREAD

**Issue by alexbfree** [zooniverse/Galaxy-Zoo#246]
Lack of data on dev server is making development of other features hard.

(see also #245)

**Comment by alexbfree** [comment]
@parrish @willettk I am not sure who is best placed to help with this, maybe one of you?

**Comment by willettk** [comment]
Likely not me - I can point to where the subject files exist, but don't
have the knowledge or credentials to add them to dev.

**Comment by alexbfree** [comment]
@parrish was it you that added them on production? would you be able to add some to dev if so?
(or TBH, reactivating a few thousand old ones would be fine if that's easier)

**Comment by parrish** [comment]
I can replace the data with the production data if that works for you.

**Comment by alexbfree** [comment]
@parrish Yeah that would be fine. If you could do that today so I can pick up tomorrow that would be awesome.

**Comment by willettk** [comment]
Clearing classifications doesn't affect production ouroboros database -
correct?

**Comment by alexbfree** [comment]
@willettk He's talking about clearing the classifications on the dev database only. Right @parrish ?

**Comment by parrish** [comment]
Yep, just clearing the classifications from the staging database.  Chances are, there would be classifications of subjects that won't exist anymore, which would probably break a few things.  I figure it's easiest to just get rid of them.

**Comment by willettk** [comment]
OK - fine by me.

**Comment by parrish** [comment]
Done!

**Comment by alexbfree** [comment]
Hi @parrish - are the group IDs different or something? because now, the dev server is instead of reporting no images, is not recognising the group ID for decals and illustris .. can you fix them to have the same group IDs they had previously? (Or offer an alternative way to get around this issue)
![screenshot](https://cloud.githubusercontent.com/assets/1473244/11869928/4a85878e-a4bb-11e5-8725-e66e87e49bed.png)

**Comment by alexbfree** [comment]
Thanks for helping me resolve this @parrish . Looks like in the end I just needed to update the dev config to have the same group IDs as production. All working now > http://preview.zooniverse.org/galaxyzoo.
