### ISSUE TITLE
GAMA example images broken

### ISSUE THREAD

**Issue by astopy** [zooniverse/Galaxy-Zoo#287]
Copied from @bamford on Slack:

> If I click one of the example images for a GAMA galaxy, it brings up a broken image.  The reason is it the `example` view constructs the wrong image url.  It appears to use the style tag (e.g., `gama-0_a-0_0.jpg`) rather than the url specified in `common.styl` (`gamakids-0_a-0_0.png`, which is correctly used for the thumbnails in the `help` view).  I didn’t realise that these needed to be identical.  I could change all the tags to `gamakids`, but I’d be concerned about breaking something else.  I think the workflow name (`gama`) may be used to create the css tag.  I guess that ideally the `example` view should use the same css trick to get the correct url.  Again, I’m afraid of trying to fix this myself in case I break something else.  An ugly (but safer) fix would be to simply add a line in example.eco doing a string replace of `gama` to `gamakids` in `@example` in `example.eco`.

https://zooniverse.slack.com/archives/galaxyzoo/p1486552910000422

**Comment by murraycu** [comment]
This would have been picked up by my tests in android-galaxyzoo. I will check and try to provide a pull request.

**Comment by murraycu** [comment]
The commits in my PR should fix the problems: https://github.com/zooniverse/Galaxy-Zoo/issues/289

However, there also seems to be a problem with these particular 2 images on the server, though the files do exist in git:
https://static.zooniverse.org/www.galaxyzoo.org/images/examples/gamakids-10_a-0_0.png
https://static.zooniverse.org/www.galaxyzoo.org/images/examples/gamakids-10_a-0_1.png
so when these corrections have been deployed, we should check that we can really see the new files:
https://static.zooniverse.org/www.galaxyzoo.org/images/examples/gama-10_a-0_0.jpg
https://static.zooniverse.org/www.galaxyzoo.org/images/examples/gama-10_a-0_1.jpg

**Comment by astopy** [comment]
@murraycu Thanks for the PR! The example images are fixed now.

I don't see the two images you mentioned in the git repo, but I see files with "10_x" rather than "10_a". I assume that's all as intended, but do feel free to open a new issue if that's not correct.

**Comment by murraycu** [comment]
@astopy Yes, sorry, I must have been confused. This seems to be the only remaining problem:
https://github.com/zooniverse/Galaxy-Zoo/pull/291

With that change, all my tests in android-galaxyzoo now pass for the gama survey.

**Comment by murraycu** [comment]
By the way, I would have preferred to have had warning when this was about to go live:
https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/models/subject.coffee#L89
