### ISSUE TITLE
Ferengi2 survey is active in client but disabled on server

### ISSUE THREAD

**Issue by murraycu** [zooniverse/Galaxy-Zoo#290]
The Ferengi2 survey is still active in the client code:
https://github.com/zooniverse/Galaxy-Zoo/blob/master/app/models/subject.coffee#L100
but the survey has apparently been disabled on the server.

For instance, this returns empty JSON:
https://www.galaxyzoo.org/_ouroboros_api/projects/galaxy_zoo/groups/58417dcb9afc3a007d000001/subjects?limit=1

So about 40% of the web client's requests for new subjects must be failing.

**Comment by CKrawczyk** [comment]
The Ferengi2 sample finished last week, we will be re-activating some paused subjects soon.

**Comment by murraycu** [comment]
Reactivating Ferengi2 subjects, or subjects in some other survey?

**Comment by murraycu** [comment]
Fixed by commit https://github.com/zooniverse/Galaxy-Zoo/commit/0a6fdef622f5bba6d4b801c36d47e936976991d0 which disables the Ferengi2 survey.
